/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BuySellItem {
  'id' : ItemId,
  'title' : string,
  'storageBlobs' : Array<ExternalBlob>,
  'description' : string,
  'category' : string,
  'sellerId' : UserId,
  'price' : Rupee,
  'isFromSellSection' : boolean,
  'condition' : string,
  'images' : Array<Uint8Array>,
}
export type ExternalBlob = Uint8Array;
export type ItemId = bigint;
export interface LostFoundItem {
  'id' : ItemId,
  'status' : string,
  'title' : string,
  'ownerId' : UserId,
  'storageBlobs' : Array<ExternalBlob>,
  'description' : string,
  'location' : string,
  'images' : Array<Uint8Array>,
}
export interface MinimalItem {
  'id' : ItemId,
  'title' : string,
  'itemType' : { 'rent' : null } |
    { 'lostFound' : null } |
    { 'buySell' : null },
  'image' : Uint8Array,
  'dailyPrice' : [] | [Rupee],
  'price' : [] | [Rupee],
}
export interface OnboardingAnswers {
  'city' : string,
  'year' : string,
  'address' : string,
}
export interface RentalItem {
  'id' : ItemId,
  'title' : string,
  'ownerId' : UserId,
  'storageBlobs' : Array<ExternalBlob>,
  'description' : string,
  'available' : boolean,
  'category' : string,
  'dailyPrice' : Rupee,
  'condition' : string,
  'images' : Array<Uint8Array>,
}
export type Rupee = bigint;
export type UserId = Principal;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'university' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBuySellItem' : ActorMethod<
    [
      string,
      string,
      Rupee,
      string,
      string,
      Array<Uint8Array>,
      Array<ExternalBlob>,
      boolean,
    ],
    undefined
  >,
  'addItem' : ActorMethod<
    [
      { 'found' : null } |
        { 'lost' : null } |
        { 'rent' : null } |
        { 'buySell' : null },
      string,
      string,
      [] | [Rupee],
      [] | [Rupee],
      [] | [string],
      [] | [string],
      [] | [string],
      Array<Uint8Array>,
      Array<ExternalBlob>,
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createUserProfile' : ActorMethod<[UserProfile], undefined>,
  'deleteItem' : ActorMethod<[ItemId], undefined>,
  'deleteLostFoundItem' : ActorMethod<[ItemId], undefined>,
  'filterBuySellItemsByCategory' : ActorMethod<[string], Array<BuySellItem>>,
  'filterBuySellItemsByPriceRange' : ActorMethod<
    [Rupee, Rupee],
    Array<BuySellItem>
  >,
  'getBuySellItem' : ActorMethod<[ItemId], [] | [BuySellItem]>,
  'getBuySellItems' : ActorMethod<[], Array<BuySellItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLostFoundItem' : ActorMethod<[ItemId], [] | [LostFoundItem]>,
  'getLostFoundItems' : ActorMethod<[], Array<LostFoundItem>>,
  'getOnboardingAnswers' : ActorMethod<[], [] | [OnboardingAnswers]>,
  'getRentalItem' : ActorMethod<[ItemId], [] | [RentalItem]>,
  'getRentalItems' : ActorMethod<[], Array<RentalItem>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listForRent' : ActorMethod<
    [
      string,
      string,
      Rupee,
      string,
      string,
      Array<Uint8Array>,
      Array<ExternalBlob>,
    ],
    undefined
  >,
  'markAsRecovered' : ActorMethod<[ItemId], undefined>,
  'postFoundItem' : ActorMethod<
    [string, string, string, Array<Uint8Array>, Array<ExternalBlob>],
    undefined
  >,
  'postLostItem' : ActorMethod<
    [string, string, string, Array<Uint8Array>, Array<ExternalBlob>],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setOnboardingAnswers' : ActorMethod<[OnboardingAnswers], undefined>,
  'toMinimalItemList' : ActorMethod<[], Array<MinimalItem>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];