/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Rupee = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'university' : IDL.Text,
});
export const ItemId = IDL.Nat;
export const UserId = IDL.Principal;
export const BuySellItem = IDL.Record({
  'id' : ItemId,
  'title' : IDL.Text,
  'storageBlobs' : IDL.Vec(ExternalBlob),
  'description' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'category' : IDL.Text,
  'sellerId' : UserId,
  'price' : Rupee,
  'isFromSellSection' : IDL.Bool,
  'condition' : IDL.Text,
  'images' : IDL.Vec(IDL.Vec(IDL.Nat8)),
});
export const LostFoundItem = IDL.Record({
  'id' : ItemId,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'ownerId' : UserId,
  'storageBlobs' : IDL.Vec(ExternalBlob),
  'description' : IDL.Text,
  'location' : IDL.Text,
  'images' : IDL.Vec(IDL.Vec(IDL.Nat8)),
});
export const OnboardingAnswers = IDL.Record({
  'city' : IDL.Text,
  'year' : IDL.Text,
  'address' : IDL.Text,
});
export const RentalItem = IDL.Record({
  'id' : ItemId,
  'title' : IDL.Text,
  'ownerId' : UserId,
  'storageBlobs' : IDL.Vec(ExternalBlob),
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'whatsappNumber' : IDL.Text,
  'category' : IDL.Text,
  'dailyPrice' : Rupee,
  'condition' : IDL.Text,
  'images' : IDL.Vec(IDL.Vec(IDL.Nat8)),
});
export const MinimalItem = IDL.Record({
  'id' : ItemId,
  'title' : IDL.Text,
  'itemType' : IDL.Variant({
    'rent' : IDL.Null,
    'lostFound' : IDL.Null,
    'buySell' : IDL.Null,
  }),
  'image' : IDL.Vec(IDL.Nat8),
  'dailyPrice' : IDL.Opt(Rupee),
  'price' : IDL.Opt(Rupee),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBuySellItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Rupee,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Vec(IDL.Nat8)),
        IDL.Vec(ExternalBlob),
        IDL.Bool,
        IDL.Text,
      ],
      [],
      [],
    ),
  'addItem' : IDL.Func(
      [
        IDL.Variant({
          'found' : IDL.Null,
          'lost' : IDL.Null,
          'rent' : IDL.Null,
          'buySell' : IDL.Null,
        }),
        IDL.Text,
        IDL.Text,
        IDL.Opt(Rupee),
        IDL.Opt(Rupee),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Vec(IDL.Nat8)),
        IDL.Vec(ExternalBlob),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'addNonUniversityPrincipal' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createUserProfile' : IDL.Func([UserProfile], [], []),
  'deleteItem' : IDL.Func([ItemId], [], []),
  'deleteLostFoundItem' : IDL.Func([ItemId], [], []),
  'filterBuySellItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BuySellItem)],
      ['query'],
    ),
  'filterBuySellItemsByPriceRange' : IDL.Func(
      [Rupee, Rupee],
      [IDL.Vec(BuySellItem)],
      ['query'],
    ),
  'getBuySellItem' : IDL.Func([ItemId], [IDL.Opt(BuySellItem)], ['query']),
  'getBuySellItems' : IDL.Func([], [IDL.Vec(BuySellItem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLostFoundItem' : IDL.Func([ItemId], [IDL.Opt(LostFoundItem)], ['query']),
  'getLostFoundItems' : IDL.Func([], [IDL.Vec(LostFoundItem)], ['query']),
  'getNonUniversityPrincipals' : IDL.Func(
      [],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getOnboardingAnswers' : IDL.Func(
      [],
      [IDL.Opt(OnboardingAnswers)],
      ['query'],
    ),
  'getRentalItem' : IDL.Func([ItemId], [IDL.Opt(RentalItem)], ['query']),
  'getRentalItems' : IDL.Func([], [IDL.Vec(RentalItem)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCampusMember' : IDL.Func([], [IDL.Bool], []),
  'isNonUniversityPrincipal' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'listForRent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Rupee,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Vec(IDL.Nat8)),
        IDL.Vec(ExternalBlob),
        IDL.Text,
      ],
      [],
      [],
    ),
  'markAsRecovered' : IDL.Func([ItemId], [], []),
  'postFoundItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Vec(IDL.Nat8)),
        IDL.Vec(ExternalBlob),
      ],
      [],
      [],
    ),
  'postLostItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Vec(IDL.Nat8)),
        IDL.Vec(ExternalBlob),
      ],
      [],
      [],
    ),
  'removeNonUniversityPrincipal' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setOnboardingAnswers' : IDL.Func([OnboardingAnswers], [], []),
  'toMinimalItemList' : IDL.Func([], [IDL.Vec(MinimalItem)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Rupee = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'university' : IDL.Text,
  });
  const ItemId = IDL.Nat;
  const UserId = IDL.Principal;
  const BuySellItem = IDL.Record({
    'id' : ItemId,
    'title' : IDL.Text,
    'storageBlobs' : IDL.Vec(ExternalBlob),
    'description' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'category' : IDL.Text,
    'sellerId' : UserId,
    'price' : Rupee,
    'isFromSellSection' : IDL.Bool,
    'condition' : IDL.Text,
    'images' : IDL.Vec(IDL.Vec(IDL.Nat8)),
  });
  const LostFoundItem = IDL.Record({
    'id' : ItemId,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'ownerId' : UserId,
    'storageBlobs' : IDL.Vec(ExternalBlob),
    'description' : IDL.Text,
    'location' : IDL.Text,
    'images' : IDL.Vec(IDL.Vec(IDL.Nat8)),
  });
  const OnboardingAnswers = IDL.Record({
    'city' : IDL.Text,
    'year' : IDL.Text,
    'address' : IDL.Text,
  });
  const RentalItem = IDL.Record({
    'id' : ItemId,
    'title' : IDL.Text,
    'ownerId' : UserId,
    'storageBlobs' : IDL.Vec(ExternalBlob),
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'whatsappNumber' : IDL.Text,
    'category' : IDL.Text,
    'dailyPrice' : Rupee,
    'condition' : IDL.Text,
    'images' : IDL.Vec(IDL.Vec(IDL.Nat8)),
  });
  const MinimalItem = IDL.Record({
    'id' : ItemId,
    'title' : IDL.Text,
    'itemType' : IDL.Variant({
      'rent' : IDL.Null,
      'lostFound' : IDL.Null,
      'buySell' : IDL.Null,
    }),
    'image' : IDL.Vec(IDL.Nat8),
    'dailyPrice' : IDL.Opt(Rupee),
    'price' : IDL.Opt(Rupee),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBuySellItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Rupee,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Vec(IDL.Nat8)),
          IDL.Vec(ExternalBlob),
          IDL.Bool,
          IDL.Text,
        ],
        [],
        [],
      ),
    'addItem' : IDL.Func(
        [
          IDL.Variant({
            'found' : IDL.Null,
            'lost' : IDL.Null,
            'rent' : IDL.Null,
            'buySell' : IDL.Null,
          }),
          IDL.Text,
          IDL.Text,
          IDL.Opt(Rupee),
          IDL.Opt(Rupee),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Vec(IDL.Nat8)),
          IDL.Vec(ExternalBlob),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'addNonUniversityPrincipal' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createUserProfile' : IDL.Func([UserProfile], [], []),
    'deleteItem' : IDL.Func([ItemId], [], []),
    'deleteLostFoundItem' : IDL.Func([ItemId], [], []),
    'filterBuySellItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BuySellItem)],
        ['query'],
      ),
    'filterBuySellItemsByPriceRange' : IDL.Func(
        [Rupee, Rupee],
        [IDL.Vec(BuySellItem)],
        ['query'],
      ),
    'getBuySellItem' : IDL.Func([ItemId], [IDL.Opt(BuySellItem)], ['query']),
    'getBuySellItems' : IDL.Func([], [IDL.Vec(BuySellItem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLostFoundItem' : IDL.Func(
        [ItemId],
        [IDL.Opt(LostFoundItem)],
        ['query'],
      ),
    'getLostFoundItems' : IDL.Func([], [IDL.Vec(LostFoundItem)], ['query']),
    'getNonUniversityPrincipals' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getOnboardingAnswers' : IDL.Func(
        [],
        [IDL.Opt(OnboardingAnswers)],
        ['query'],
      ),
    'getRentalItem' : IDL.Func([ItemId], [IDL.Opt(RentalItem)], ['query']),
    'getRentalItems' : IDL.Func([], [IDL.Vec(RentalItem)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCampusMember' : IDL.Func([], [IDL.Bool], []),
    'isNonUniversityPrincipal' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'listForRent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Rupee,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Vec(IDL.Nat8)),
          IDL.Vec(ExternalBlob),
          IDL.Text,
        ],
        [],
        [],
      ),
    'markAsRecovered' : IDL.Func([ItemId], [], []),
    'postFoundItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Vec(IDL.Nat8)),
          IDL.Vec(ExternalBlob),
        ],
        [],
        [],
      ),
    'postLostItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Vec(IDL.Nat8)),
          IDL.Vec(ExternalBlob),
        ],
        [],
        [],
      ),
    'removeNonUniversityPrincipal' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setOnboardingAnswers' : IDL.Func([OnboardingAnswers], [], []),
    'toMinimalItemList' : IDL.Func([], [IDL.Vec(MinimalItem)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };